// Color constants and mock datasets for Medical Supply Intelligence Entry Page

export const ENTRY_COLORS = {
  primary: '#023625',
  primaryContainer: '#1f4d3a',
  onPrimary: '#ffffff',
  background: '#f0fdf3',
  surface: '#f0fdf3',
  surfaceContainer: '#e4f1e7',
  surfaceContainerHigh: '#dfebe2',
  surfaceContainerLow: '#eaf7ed',
  surfaceContainerLowest: '#ffffff',
  onSurface: '#131e18',
  onSurfaceVariant: '#414944',
  secondaryContainer: '#dbe6d8',
  error: '#ba1a1a',
  errorContainer: '#ffdad6',
  warningBg: '#FFF4DD',
  warningText: '#E8A33D',
  criticalBg: '#FDECEC',
  criticalText: '#D64545',
  successBg: '#E3F6EA',
  successGreen: '#2FA866',
  leafBannerBg: '#DDE8DA',
};

export const MOCK_HOSPITAL_PROFILE = {
  name: 'Hospital A (Central General)',
  shortName: 'Hospital A',
  beds: 450,
  location: 'North District · Sector 4 Regional Grid',
  initial: 'A',
};

export const MOCK_MEDICINES = [
  {
    id: 'med-amox-500',
    name: 'Amoxicillin 500mg (Capsules/Tablets)',
    unit: 'tablets',
    currentStock: 1200,
    expectedDemand14Days: 2800,
    usualRequestAmount: 160,
    existingBatches: ['AMX-8102', 'AMX-7740', 'AMX-9011'],
  },
  {
    id: 'med-ceft-1g',
    name: 'Ceftriaxone 1g (Vial)',
    unit: 'vials',
    currentStock: 800,
    expectedDemand14Days: 1400,
    usualRequestAmount: 100,
    existingBatches: ['CFT-4410', 'CFT-3820'],
  },
  {
    id: 'med-salb-100',
    name: 'Salbutamol 100mcg (Inhaler)',
    unit: 'inhalers',
    currentStock: 350,
    expectedDemand14Days: 700,
    usualRequestAmount: 50,
    existingBatches: ['SLB-2099', 'SLB-1011'],
  },
  {
    id: 'med-morph-10',
    name: 'Morphine 10mg (Ampoule)',
    unit: 'ampoules',
    currentStock: 150,
    expectedDemand14Days: 320,
    usualRequestAmount: 20,
    existingBatches: ['MRP-9932', 'MRP-8421'],
  },
  {
    id: 'med-para-1g',
    name: 'Paracetamol 1g IV (Infusion bag)',
    unit: 'infusion bags',
    currentStock: 1500,
    expectedDemand14Days: 2600,
    usualRequestAmount: 200,
    existingBatches: ['PCM-9021', 'PCM-8140'],
  },
];

export const INITIAL_RECENT_ENTRIES = [
  {
    id: 'rec-1',
    title: 'Request: Amoxicillin 500mg',
    time: 'Just now',
    pillText: '1,600 tablets · Urgent',
    pillType: 'urgent',
    subtitle: 'Needed by Oct 12 · Looking for stock',
  },
  {
    id: 'rec-2',
    title: 'Amoxicillin 500mg',
    time: '10 min ago',
    pillText: '+2,000 units received',
    pillType: 'received',
    subtitle: 'Batch #AMX-8102',
  },
  {
    id: 'rec-3',
    title: 'Salbutamol 100mcg',
    time: '2 hours ago',
    pillText: '-180 units used',
    pillType: 'used',
    subtitle: 'Ward inventory draw',
  },
  {
    id: 'rec-4',
    title: 'Ceftriaxone 1g',
    time: 'Yesterday, 16:40',
    pillText: '+800 units received',
    pillType: 'received',
    subtitle: 'Batch #CFT-4410',
  },
  {
    id: 'rec-5',
    title: 'Morphine 10mg',
    time: 'Yesterday, 11:15',
    pillText: '-45 units used',
    pillType: 'used',
    subtitle: 'ICU & Surgery pool',
  },
  {
    id: 'rec-6',
    title: 'Paracetamol 1g IV',
    time: '2 days ago',
    pillText: '+1,500 units received',
    pillType: 'received',
    subtitle: 'Batch #PCM-9021',
  },
];
